title: "CausNetS @ NetSci 2026"
description: "Satellite workshop on Causal Network Science at NetSci 2026"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
markdown: kramdown
show_feed: false
nav:
  - title: "Submit Abstract"
    url: /submit/
  - title: "Schedule"
    url: /schedule/
  - title: "Invited Speakers"
    url: /speakers/
  - title: "Contact"
    url: "mailto:"
  - title: "Register for NetSci"
    url: "https://www.netsci2026.com/registration"
  - label: "About NetSci"
    url: "https://www.netsci2026.com"
