title: "CausNetS @ NetSci 2026"
description: "Satellite workshop on Causal Network Science at NetSci 2026"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-include-cache
markdown: kramdown
atom_feed:
  hide: true
