title: "CausNetS"
description: "Satellite workshop on Causal Network Science at NetSci 2026"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-include-cache
markdown: kramdown
atom_feed:
  hide: true
logo: "/assets/images/causnets_logo.png"
favicon: "/assets/images/causnets_logo.png"
sidebar:
  - title: "Important Dates"
    text: "- Submission deadline: **March (TBD), 2026**  
    - Notification of acceptance: **March (TBD), 2026**
    - Early-bird registration deadline: **March 20, 2026**
    - Satellite date: **June 1, 2026**"
