title: "CausNetS @ NetSci 2026"
description: "Satellite workshop on Causal Network Science at NetSci 2026"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
markdown: kramdown
atom_feed:
  hide: true
header:
  nav:
    - title: "Submit Abstract"
      url: /submit/
    - title: "Schedule"
      url: /schedule/
    - title: "Invited Speakers"
      url: /speakers/
    - title: "Contact"
      url: "mailto:"
    - title: "Register for NetSci"
      url: "https://www.netsci2026.com/registration"
    - title: "About NetSci"
      url: "https://www.netsci2026.com"
