title: "CausNetS @ NetSci 2026"
description: "Satellite workshop on Causal Network Science at NetSci 2026"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
markdown: kramdown
show_feed: false
